language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - bash .travis/setup_beanstalkd.sh
  - luarocks install luasocket
  - luarocks install penlight
  - luarocks install cwtest
  - luarocks install lyaml

before_script:
  - beanstalkd &
  - sleep 1

script:
  - lua haricot.test.lua

notifications:
  email:
    on_success: change
    on_failure: always
